// Ctrl + K then Ctrl + 0 (zero) = collapse all
// Ctrl + K then Ctrl + J = expand all

export const contentRatingFilters = [
  { value: "clean", label: "Clean (No explicit content)" },
  { value: "mild", label: "Mild (Some mature themes)" },
  { value: "moderate", label: "Moderate (Some explicit content)" },
  { value: "steamy", label: "Steamy (Explicit intimate scenes)" },
  { value: "dark", label: "Dark (Potentially disturbing themes)" },
  { value: "fade-to-black", label: "Fade to Black (Intimate scenes implied)" },
  { value: "trigger-warnings", label: "Contains Trigger Warnings" },
];

export const representationFilters = [
  { value: "lgbtqia", label: "LGBTQIA+" },
  { value: "sapphic", label: "Sapphic (WLW)" },
  { value: "achillean", label: "Achillean (MLM)" },
  { value: "bipoc", label: "BIPOC" },
  { value: "ownvoices", label: "Own Voices" },
  { value: "neurodivergent", label: "Neurodivergent" },
  { value: "disability", label: "Disability" },
  { value: "poc-author", label: "POC Author" },
  { value: "queer-author", label: "Queer Author" },
];

export const romanceTropeOptions = [
  { value: "enemies-to-lovers", label: "Enemies to Lovers" },
  { value: "second-chance", label: "Second Chance" },
  { value: "meet-cute", label: "Meet-Cute" },
  { value: "forced-proximity", label: "Forced Proximity" },
  { value: "forbidden-love", label: "Forbidden Love" },
  { value: "love-triangle", label: "Love Triangle" },
  { value: "fake-relationship", label: "Fake Relationship" },
  { value: "slow-burn", label: "Slow Burn" },
  { value: "opposites-attract", label: "Opposites Attract" },
  { value: "friends-to-lovers", label: "Friends to Lovers" },
  { value: "reverse-harem", label: "Reverse Harem" },
  { value: "harem", label: "Harem" },
  { value: "w-w", label: "Woman/Woman (W/W)" },
  { value: "m-m", label: "Man/Man (M/M)" },
  { value: "m-f", label: "Man/Woman (M/F)" },
  { value: "hea", label: "Happily Ever After (HEA)" },
  { value: "hfn", label: "Happy For Now (HFN)" },
];

export const trueCrimeTropeOptions = [
  { value: "cold-cases", label: "Cold Cases" },
  { value: "serial-killers", label: "Serial Killers" },
  { value: "unsolved-mysteries", label: "Unsolved Mysteries" },
  { value: "wrongful-convictions", label: "Wrongful Convictions" },
  { value: "forensic-analysis", label: "Forensic Analysis" },
  { value: "police-procedurals", label: "Police Procedurals" },
  { value: "courtroom-dramas", label: "Courtroom Dramas" },
  { value: "investigative-journalism", label: "Investigative Journalism" },
  { value: "historical-crimes", label: "Historical Crimes" },
  { value: "organized-crime", label: "Organized Crime/Mafia" },
  { value: "white-collar-crimes", label: "White-Collar Crimes" },
  { value: "cults", label: "Cults and Cult Leaders" },
  { value: "conspiracy-theories", label: "Conspiracy Theories" },
  { value: "miscarriages-of-justice", label: "Miscarriages of Justice" },
  {
    value: "true-crime-podcasts",
    label: "True Crime Podcasts (Book Adaptations)",
  },
  { value: "crime-scene-reconstruction", label: "Crime Scene Reconstruction" },
  { value: "psychological-profiling", label: "Psychological Profiling" },
  { value: "survivor-stories", label: "Survivor Stories" },
  { value: "heists-and-robberies", label: "Heists and Robberies" },
  { value: "crime-family-dynasties", label: "Crime Family Dynasties" },
];

export const thrillerTropeOptions = [
  { value: "unreliable-narrator", label: "Unreliable Narrator" },
  { value: "race-against-time", label: "Race Against Time" },
  { value: "conspiracy", label: "Conspiracy" },
  { value: "mistaken-identity", label: "Mistaken Identity" },
  { value: "cat-and-mouse", label: "Cat and Mouse Chase" },
  { value: "psychological-manipulation", label: "Psychological Manipulation" },
  { value: "double-cross", label: "Double Cross" },
  { value: "false-accusation", label: "False Accusation" },
  { value: "amnesia", label: "Amnesia" },
  { value: "red-herring", label: "Red Herring" },
  { value: "femme-fatale", label: "Femme Fatale" },
  { value: "ticking-time-bomb", label: "Ticking Time Bomb" },
  { value: "locked-room-mystery", label: "Locked Room Mystery" },
  { value: "government-coverup", label: "Government Cover-up" },
  { value: "revenge-plot", label: "Revenge Plot" },
  { value: "serial-killer", label: "Serial Killer" },
  { value: "sleeper-agent", label: "Sleeper Agent" },
  { value: "blackmail", label: "Blackmail" },
  { value: "missing-person", label: "Missing Person" },
  { value: "stalker", label: "Stalker" },
];

export const sciFiTropeOptions = [
  { value: "time-travel", label: "Time Travel" },
  { value: "alien-invasion", label: "Alien Invasion" },
  { value: "space-exploration", label: "Space Exploration" },
  { value: "artificial-intelligence", label: "Artificial Intelligence" },
  { value: "dystopian-future", label: "Dystopian Future" },
  { value: "post-apocalyptic", label: "Post-Apocalyptic" },
  { value: "parallel-universes", label: "Parallel Universes" },
  { value: "cyberpunk", label: "Cyberpunk" },
  { value: "genetic-engineering", label: "Genetic Engineering" },
  { value: "first-contact", label: "First Contact" },
  { value: "space-opera", label: "Space Opera" },
  { value: "robot-uprising", label: "Robot Uprising" },
  { value: "terraforming", label: "Terraforming" },
  { value: "virtual-reality", label: "Virtual Reality" },
  { value: "mind-uploading", label: "Mind Uploading" },
  { value: "generation-ships", label: "Generation Ships" },
  { value: "alternate-history", label: "Alternate History" },
  { value: "time-loop", label: "Time Loop" },
  { value: "nanobots", label: "Nanobots" },
  { value: "cloning", label: "Cloning" },
];

export const fantasyTropeOptions = [
  { value: "chosen-one", label: "The Chosen One" },
  { value: "magic-school", label: "Magic School" },
  { value: "quest", label: "Epic Quest" },
  { value: "dragons", label: "Dragons" },
  { value: "elves-dwarves", label: "Elves and Dwarves" },
  { value: "dark-lord", label: "Dark Lord" },
  { value: "magical-artifacts", label: "Magical Artifacts" },
  { value: "coming-of-age", label: "Coming of Age" },
  { value: "portal-fantasy", label: "Portal to Another World" },
  { value: "prophecy", label: "Ancient Prophecy" },
  { value: "magical-creatures", label: "Magical Creatures" },
  { value: "wizard-mentor", label: "Wizard Mentor" },
  { value: "hidden-royalty", label: "Hidden Royalty" },
  { value: "magical-powers", label: "Discovering Magical Powers" },
  { value: "good-vs-evil", label: "Good vs. Evil" },
  { value: "mythical-lands", label: "Mythical Lands" },
  { value: "magical-races", label: "Magical Races" },
  { value: "unlikely-hero", label: "Unlikely Hero" },
  { value: "magical-systems", label: "Complex Magical Systems" },
  { value: "talking-animals", label: "Talking Animals" },
];

export const genres = [
  { value: "fiction", label: "Fiction" },
  { value: "non-fiction", label: "Non-fiction" },
  { value: "mystery", label: "Mystery" },
  { value: "romance", label: "Romance" },
  { value: "thriller", label: "Thriller" },
  { value: "science-fiction", label: "Science fiction" },
  { value: "fantasy", label: "Fantasy" },
  { value: "young-adult", label: "Young adult" },
  { value: "bestseller", label: "Bestseller" },
  { value: "biography", label: "Biography" },
  { value: "history", label: "History" },
  { value: "self-help", label: "Self-help" },
  { value: "childrens-books", label: "Children's books" },
  { value: "crime", label: "Crime" },
  { value: "contemporary-fiction", label: "Contemporary fiction" },
  { value: "historical-fiction", label: "Historical fiction" },
  { value: "classic-literature", label: "Classic literature" },
  { value: "literary-fiction", label: "Literary fiction" },
  { value: "horror", label: "Horror" },
  { value: "memoir", label: "Memoir" },
  { value: "business", label: "Business" },
  { value: "true-crime", label: "True crime" },
  { value: "cooking", label: "Cooking" },
  { value: "graphic-novel", label: "Graphic novel" },
  { value: "adventure", label: "Adventure" },
  { value: "psychology", label: "Psychology" },
  { value: "science", label: "Science" },
  { value: "travel", label: "Travel" },
  { value: "humor", label: "Humor" },
  { value: "dystopian", label: "Dystopian" },
  { value: "paranormal", label: "Paranormal" },
  { value: "health-and-wellness", label: "Health and wellness" },
  { value: "coming-of-age", label: "Coming-of-age" },
  { value: "suspense", label: "Suspense" },
  { value: "philosophy", label: "Philosophy" },
  { value: "politics", label: "Politics" },
  { value: "short-stories", label: "Short stories" },
  { value: "poetry", label: "Poetry" },
  { value: "autobiography", label: "Autobiography" },
  { value: "erotica", label: "Erotica" },
  { value: "technology", label: "Technology" },
  { value: "religion", label: "Religion" },
  { value: "art", label: "Art" },
  { value: "education", label: "Education" },
  { value: "sports", label: "Sports" },
  { value: "essays", label: "Essays" },
  { value: "music", label: "Music" },
  { value: "war", label: "War" },
  { value: "drama", label: "Drama" },
  { value: "reference", label: "Reference" },
];

export const extendedBookSearchShorthand = [
  { value: "w-w", label: "Woman/Woman relationship" },
  { value: "m-m", label: "Man/Man relationship" },
  { value: "m-f", label: "Man/Woman relationship" },
  { value: "reverse-harem", label: "Multiple men/One woman" },
  { value: "m-m-w", label: "Two men/One woman" },
  { value: "harem", label: "One man/Multiple women" },
  { value: "f-f", label: "Woman/Woman relationship (alternative to W/W)" },
  { value: "m-m-m", label: "Multiple men relationship" },
  { value: "f-f-f", label: "Multiple women relationship" },
  { value: "poly", label: "Polyamorous relationship" },
  { value: "lgbtqia", label: "LGBTQIA+ representation" },
  { value: "ace", label: "Asexual representation" },
  { value: "aro", label: "Aromantic representation" },
  { value: "bi", label: "Bisexual representation" },
  { value: "pan", label: "Pansexual representation" },
  { value: "trans", label: "Transgender representation" },
  { value: "nb", label: "Non-binary representation" },
  { value: "gq", label: "Genderqueer representation" },
  { value: "hea", label: "Happily Ever After" },
  { value: "hfn", label: "Happy For Now" },
  { value: "na", label: "New Adult" },
  { value: "ya", label: "Young Adult" },
  { value: "mg", label: "Middle Grade" },
  { value: "cr", label: "Contemporary Romance" },
  { value: "hr", label: "Historical Romance" },
  { value: "pr", label: "Paranormal Romance" },
  { value: "sr", label: "Sci-Fi Romance" },
  { value: "er", label: "Erotic Romance" },
  { value: "dnf", label: "Did Not Finish" },
  { value: "mc", label: "Main Character" },
  { value: "mmc", label: "Male Main Character" },
  { value: "fmc", label: "Female Main Character" },
  { value: "poc", label: "Person of Color" },
  { value: "bipoc", label: "Black, Indigenous, Person of Color" },
  {
    value: "own-voices",
    label: "Author from marginalized group writing about their experiences",
  },
  { value: "otp", label: "One True Pairing" },
  { value: "notp", label: "Not One True Pairing" },
  { value: "tstl", label: "Too Stupid To Live" },
  { value: "pwp", label: "Plot? What Plot? or Porn Without Plot" },
  { value: "au", label: "Alternate Universe" },
  { value: "abo", label: "Alpha/Beta/Omega dynamics" },
  { value: "ust", label: "Unresolved Sexual Tension" },
  { value: "rst", label: "Resolved Sexual Tension" },
  { value: "ftb", label: "Fade To Black" },
  { value: "tw", label: "Trigger Warning" },
  { value: "cw", label: "Content Warning" },
  { value: "ott", label: "Over The Top" },
  { value: "ic", label: "In Character" },
  { value: "ooc", label: "Out Of Character" },
  { value: "wip", label: "Work In Progress" },
  { value: "rh", label: "Reverse Harem" },
  { value: "pnr", label: "Paranormal Romance" },
  { value: "uf", label: "Urban Fantasy" },
  { value: "ku", label: "Kindle Unlimited" },
  { value: "tbr", label: "To Be Read" },
  { value: "ov", label: "Own Voices" },
  { value: "hp", label: "High Heat" },
  { value: "lh", label: "Low Heat" },
];
