export const shorthandMapping = {
  "w/w": "woman on woman",
  "m/m": "man on man",
  "m/f": "man and woman",
  "reverse harem": "reverse harem",
  "m/m/w": "reverse harem",
  harem: "harem",
  lgbtq: "LGBTQ",
  sapphic: "sapphic",
};

export const tropeMapping = {
  "enemies to lovers": "enemies to lovers",
  "second chance": "second chance",
  "meet-cute": "meet-cute",
  "forced proximity": "forced proximity",
  "forbidden love": "forbidden love",
  "love triangle": "love triangle",
  "fake relationship": "fake relationship",
  "slow burn": "slow burn",
  "opposites attract": "opposites attract",
  "friends to lovers": "friends to lovers",
};

export const genres = [
  { value: "fiction", label: "Fiction" },
  { value: "non-fiction", label: "Non-fiction" },
  { value: "mystery", label: "Mystery" },
  { value: "romance", label: "Romance" },
  { value: "thriller", label: "Thriller" },
  { value: "science-fiction", label: "Science fiction" },
  { value: "fantasy", label: "Fantasy" },
  { value: "biography", label: "Biography" },
  { value: "history", label: "History" },
  { value: "self-help", label: "Self-help" },
  { value: "bestseller", label: "Bestseller" },
  { value: "classic-literature", label: "Classic literature" },
  { value: "young-adult", label: "Young adult" },
  { value: "childrens-books", label: "Children's books" },
  { value: "poetry", label: "Poetry" },
  { value: "crime", label: "Crime" },
  { value: "horror", label: "Horror" },
  { value: "adventure", label: "Adventure" },
  { value: "contemporary-fiction", label: "Contemporary fiction" },
  { value: "historical-fiction", label: "Historical fiction" },
  { value: "literary-fiction", label: "Literary fiction" },
  { value: "memoir", label: "Memoir" },
  { value: "philosophy", label: "Philosophy" },
  { value: "psychology", label: "Psychology" },
  { value: "business", label: "Business" },
  { value: "cooking", label: "Cooking" },
  { value: "travel", label: "Travel" },
  { value: "art", label: "Art" },
  { value: "science", label: "Science" },
  { value: "politics", label: "Politics" },
  { value: "religion", label: "Religion" },
  { value: "graphic-novel", label: "Graphic novel" },
  { value: "humor", label: "Humor" },
  { value: "true-crime", label: "True crime" },
  { value: "dystopian", label: "Dystopian" },
  { value: "paranormal", label: "Paranormal" },
  { value: "coming-of-age", label: "Coming-of-age" },
  { value: "short-stories", label: "Short stories" },
  { value: "essays", label: "Essays" },
  { value: "technology", label: "Technology" },
  { value: "health-and-wellness", label: "Health and wellness" },
  { value: "education", label: "Education" },
  { value: "sports", label: "Sports" },
  { value: "music", label: "Music" },
  { value: "drama", label: "Drama" },
  { value: "war", label: "War" },
  { value: "suspense", label: "Suspense" },
  { value: "erotica", label: "Erotica" },
  { value: "autobiography", label: "Autobiography" },
  { value: "reference", label: "Reference" },
];
