export const contentRatingFilters = [
  { value: "clean", label: "Clean (No explicit content)" },
  { value: "mild", label: "Mild (Some mature themes)" },
  { value: "moderate", label: "Moderate (Some explicit content)" },
  { value: "steamy", label: "Steamy (Explicit intimate scenes)" },
  { value: "dark", label: "Dark (Potentially disturbing themes)" },
  { value: "fade-to-black", label: "Fade to Black (Intimate scenes implied)" },
  { value: "trigger-warnings", label: "Contains Trigger Warnings" },
];

export const representationFilters = [
  { value: "lgbtqia", label: "LGBTQIA+" },
  { value: "sapphic", label: "Sapphic (WLW)" },
  { value: "achillean", label: "Achillean (MLM)" },
  { value: "bipoc", label: "BIPOC" },
  { value: "ownvoices", label: "Own Voices" },
  { value: "neurodivergent", label: "Neurodivergent" },
  { value: "disability", label: "Disability" },
  { value: "poc-author", label: "POC Author" },
  { value: "queer-author", label: "Queer Author" },
];

export const romanceTropeOptions = [
  { value: "enemies-to-lovers", label: "Enemies to Lovers" },
  { value: "second-chance", label: "Second Chance" },
  { value: "meet-cute", label: "Meet-Cute" },
  { value: "forced-proximity", label: "Forced Proximity" },
  { value: "forbidden-love", label: "Forbidden Love" },
  { value: "love-triangle", label: "Love Triangle" },
  { value: "fake-relationship", label: "Fake Relationship" },
  { value: "slow-burn", label: "Slow Burn" },
  { value: "opposites-attract", label: "Opposites Attract" },
  { value: "friends-to-lovers", label: "Friends to Lovers" },
  { value: "reverse-harem", label: "Reverse Harem" },
  { value: "harem", label: "Harem" },
  { value: "w-w", label: "Woman/Woman (W/W)" },
  { value: "m-m", label: "Man/Man (M/M)" },
  { value: "m-f", label: "Man/Woman (M/F)" },
  { value: "hea", label: "Happily Ever After (HEA)" },
  { value: "hfn", label: "Happy For Now (HFN)" },
];

export const trueCrimeTropeOptions = [
  { value: "cold-cases", label: "Cold Cases" },
  { value: "serial-killers", label: "Serial Killers" },
  { value: "unsolved-mysteries", label: "Unsolved Mysteries" },
  { value: "wrongful-convictions", label: "Wrongful Convictions" },
  { value: "forensic-analysis", label: "Forensic Analysis" },
  { value: "police-procedurals", label: "Police Procedurals" },
  { value: "courtroom-dramas", label: "Courtroom Dramas" },
  { value: "investigative-journalism", label: "Investigative Journalism" },
  { value: "historical-crimes", label: "Historical Crimes" },
  { value: "organized-crime", label: "Organized Crime/Mafia" },
  { value: "white-collar-crimes", label: "White-Collar Crimes" },
  { value: "cults", label: "Cults and Cult Leaders" },
  { value: "conspiracy-theories", label: "Conspiracy Theories" },
  { value: "miscarriages-of-justice", label: "Miscarriages of Justice" },
  {
    value: "true-crime-podcasts",
    label: "True Crime Podcasts (Book Adaptations)",
  },
  { value: "crime-scene-reconstruction", label: "Crime Scene Reconstruction" },
  { value: "psychological-profiling", label: "Psychological Profiling" },
  { value: "survivor-stories", label: "Survivor Stories" },
  { value: "heists-and-robberies", label: "Heists and Robberies" },
  { value: "crime-family-dynasties", label: "Crime Family Dynasties" },
];

export const genres = [
  { value: "fiction", label: "Fiction" },
  { value: "non-fiction", label: "Non-fiction" },
  { value: "mystery", label: "Mystery" },
  { value: "romance", label: "Romance" },
  { value: "thriller", label: "Thriller" },
  { value: "science-fiction", label: "Science fiction" },
  { value: "fantasy", label: "Fantasy" },
  { value: "young-adult", label: "Young adult" },
  { value: "bestseller", label: "Bestseller" },
  { value: "biography", label: "Biography" },
  { value: "history", label: "History" },
  { value: "self-help", label: "Self-help" },
  { value: "childrens-books", label: "Children's books" },
  { value: "crime", label: "Crime" },
  { value: "contemporary-fiction", label: "Contemporary fiction" },
  { value: "historical-fiction", label: "Historical fiction" },
  { value: "classic-literature", label: "Classic literature" },
  { value: "literary-fiction", label: "Literary fiction" },
  { value: "horror", label: "Horror" },
  { value: "memoir", label: "Memoir" },
  { value: "business", label: "Business" },
  { value: "true-crime", label: "True crime" },
  { value: "cooking", label: "Cooking" },
  { value: "graphic-novel", label: "Graphic novel" },
  { value: "adventure", label: "Adventure" },
  { value: "psychology", label: "Psychology" },
  { value: "science", label: "Science" },
  { value: "travel", label: "Travel" },
  { value: "humor", label: "Humor" },
  { value: "dystopian", label: "Dystopian" },
  { value: "paranormal", label: "Paranormal" },
  { value: "health-and-wellness", label: "Health and wellness" },
  { value: "coming-of-age", label: "Coming-of-age" },
  { value: "suspense", label: "Suspense" },
  { value: "philosophy", label: "Philosophy" },
  { value: "politics", label: "Politics" },
  { value: "short-stories", label: "Short stories" },
  { value: "poetry", label: "Poetry" },
  { value: "autobiography", label: "Autobiography" },
  { value: "erotica", label: "Erotica" },
  { value: "technology", label: "Technology" },
  { value: "religion", label: "Religion" },
  { value: "art", label: "Art" },
  { value: "education", label: "Education" },
  { value: "sports", label: "Sports" },
  { value: "essays", label: "Essays" },
  { value: "music", label: "Music" },
  { value: "war", label: "War" },
  { value: "drama", label: "Drama" },
  { value: "reference", label: "Reference" },
];
